name: Laravel Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Step 3: Install NPM dependencies and build assets
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Assets
        run: npm run build

      # Step 4: Set Directory Permissions
      - name: Set Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      # Step 5: Deploy to DigitalOcean
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # The private key for SSH connection
          SERVER_USER: ${{ secrets.SERVER_USER }}          # The username for the server
          SERVER_IP: ${{ secrets.SERVER_IP }}              # The IP address of the server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/portfolio  # Navigate to your project directory
            git pull origin master   # Pull the latest code from GitHub
            composer install --no-dev --optimize-autoloader  # Install production dependencies
            php artisan migrate --force  # Run migrations if necessary
            php artisan config:cache  # Cache configuration
            php artisan route:cache   # Cache routes
            php artisan view:cache     # Cache views
          EOF
