name: Laravel Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Step 3: Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Step 4: Install NPM dependencies and build assets
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Assets
        run: npm run build

      # Step 5: Directory Permissions
      - name: Set Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      # Step 6: Create SSH directory and add Droplet to known hosts
      - name: Set up SSH for deployment
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 167.71.128.214 >> ~/.ssh/known_hosts

      # Step 7: Set up SSH for deployment to DigitalOcean Droplet
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      # Step 8: Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@167.71.128.214 "cd /var/www/portfolio && git pull origin master && composer install --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run build && php artisan migrate --force || exit 1"
